ALTER TABLE "GameSession"
  ADD COLUMN "lives" INTEGER NOT NULL DEFAULT 3,
  ADD COLUMN "streak" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "currentChallengeIndex" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "currentChallengeStartedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "hintCounts" JSONB NOT NULL DEFAULT '{}';
